### ISSUE TITLE
Autocorrelation

### ISSUE THREAD

**Issue by CamFreshwater** [CamFreshwater/synchSalmon#11]
Hey @ann-marieH could you help me address Carrie's comment below? 

"Can we pers. comm. Ann-Marie or Sue Grant, or reference early FRSSI material or FRSS forecasts, given their decisions to not include AR-1 due to small effects?
Since AMH is a co-author, pers. comm. may not be appropriate for her."

Basically we need justification for using weak (or no) temporal autocorrelation in Fraser residuals. Has that been documented in any Fraser pubs?

**Comment by ann-marieH** [comment]
not that I know of. I'll ask Sue/Bronwyn & cc you.

I do have some plots kicking around somewhere.

**Comment by CamFreshwater** [comment]
Quick update for the group as a whole. It doesn't seem as though these have been explicitly documented in a publication. A handful of papers have estimated autocorrelation parameters for Fraser sockeye. I would suggest using the mean across stocks from the most recent relevant publication and then demonstrating in the sensitivity analysis that higher/lower values don't dramatically influence results. Alternatively we could estimate it ourselves, but considering its impact (in terms of driving differences among synch/compCV treatments) is basically nil I'm not sure if it's worth it.

**Comment by seananderson** [comment]
Sounds fine to use a reasonable value from a recent publication. I don't think you necessarily need to include the results of a sensitivity analysis on it — it's not a main feature of the study. Could mention you checked it if you want but results aren't shown.
