### ISSUE TITLE
Skewed normal/student-t bias

### ISSUE THREAD

**Issue by seananderson** [CamFreshwater/synchSalmon#12]
I meant to mention this before, but just wanted to make sure you're aware and OK with the skewed normal and t distributions having some pretty strong mean-bias. In some situations that's fine, and it's probably fine here too, but it's important to be aware that the skewness is not only changing the shape of the deviations but also lowering the mean productivity for the simple reason that its mean is not zero in addition to any complicated non-linear effects from the simulation. It would also be possible to adjust the distribution so that its mean is zero and I've seen that done in some model-fitting papers. I think it's fine not to do that here, but it might be worth being upfront about it in the paper.

**Comment by CamFreshwater** [comment]
Yeah I recognized a few months ago that they do dramatically shift the mean downwards, although I didnt connect those dots initially. I'd agree that it's probably ok for this situation and will add an explicit note to the methods. However if you think the edited methods are inaccurate in their description of the distributions in any way please edit accordingly! On a related note I'll have revisions out early next week. Just need to rerun the sims and finish editing the discussion.
