### ISSUE TITLE
Public repos and incomplete packages

### ISSUE THREAD

**Issue by CamFreshwater** [CamFreshwater/synchSalmon#13]
Something that came up while I was talking to Carrie and Kendra today was what to do about making the synchrony repo public once we submit the manuscript. Specifically how do we address the issue that the analyses within the synchSalmon are dependent on the `samSim` package, which is still very much under development. Publishing this repo, but keeping the package private isn't an option because the `recoverySim()` function will inevitably break, making the public code fairly useless. Alternatively keeping the package public while under-development is also suboptimal. 

We came up with three options, none of which seem perfect.

1. Include a stripped down `prototypeSamSim` package that is intended solely to be used to with archived versions of this repo's code. I.e. it won't be updated and won't be exhaustively documented. This seems like it would work, but could be a little confusing.
2. Make and freeze a branch of samSim that represents all the functions in their state when the synchSalmon repo goes up. This seems like another good option, but we weren't sure if it's possible to make just one branch of a repo public while keeping the rest private. If not, it's not really a viable option.
3. Include the relevant functions (i.e. the "guts" of `samSim`) as stand-alone code with this repo. Again this will work, but it seems like a step backward when I've gone to the trouble to document each function and provide examples for many of them.
4. A fourth option that is even more old school and I just thought of is to exclude the model and core functions all together supplying only the model output and post-processing scripts. Again far from ideal from a transparency standpoint, but it may technically meet the bar of making the data accessible from an editorial board's perspective.

Any thoughts? @seananderson this seems like it may have been something you've encountered before...

**Comment by seananderson** [comment]
Probably easiest to talk in person this week, but in general:

GitHub is not an archival site anyways. You’ll want to archive a snapshot somewhere like Zenodo and cite the DOI and link back to that on GitHub. Zenodo is guaranteed to be around for decades and you can’t delete things off it. 

Yes, I’d share all the code so it’s fully reproducible.

I wouldn’t worry about everything not being perfect yet. It never is. That’s what code licenses and disclaimers and readme pages are for. In my experience, the risk of nobody noticing or using your work exceeds the risk of someone misusing your code.

You’ll want to make a Git release for whatever version is used in the published paper. Zenodo can grab that release and assign a DOI.

Packages come with version numbers and any future code can depend on a newer version of the package.

I'm all for developing out in the open in public whenever possible. David Robinson has a nice presentation he often gives on this:

https://twitter.com/JennyBryan/status/863177623999987712
or
https://twitter.com/drob/status/930492543187513345

**Comment by CamFreshwater** [comment]
Thanks for the tips Sean. I think I agree on the whole, but it would be great to talk in person later this week about how we can use archived code beyond github to address these sorts of issues!
