### ISSUE TITLE
Pooling Scotch and Seymour to create Shuswap-ES

### ISSUE THREAD

**Issue by CamFreshwater** [CamFreshwater/synchSalmon#5]
Grant et al. 2011 appear to have estimated status for Shuswap-ES by cropping the productivity time series for Scotch and Seymour at 1980 (when Scotch stopped being enhanced), then summing the two stocks. It's easy enough for me to do this for the retrospective analysis, but it's going to strongly impact the stock recruit parameter estimates that are used in the forward simulation. 

AMH, do you happen to have posterior estimates for these two pooled? I'm happy to estimate the parameters myself, but would rather not go down that road at this late stage if it can be avoided...

**Comment by CamFreshwater** [comment]
I also just remembered that one is considered cyclic and the other non-cyclic. I.e. if we do decide to pool them and refit a stock-recruit model, I'd need some advice on which model to use. Or else just assume that model selection knows best...

**Comment by ann-marieH** [comment]
I pooled them once, on a lark, many moons and datasets ago. So neither at hand nor current, sorry.

I think we used model selection methods to declare one cyclic and one not, so I'd say stick with the same logic and apply it to the pooled time series.

**Comment by CamFreshwater** [comment]
Cool beans. Can you send me the model script you used to generate the estimates? I'll probably end up translating it into JAGS (or maybe try Stan), but I just want to make sure the parameterization is correct. You could even use your powers as a collaborator to push it to the remote repo ;)!

**Comment by CamFreshwater** [comment]
One more question, for FRSSI you fit recruits to ETS not EFF correct when estimating stock-recruit parameters correct?

**Comment by ann-marieH** [comment]
currently, neither ETS or EFF. for FRSSI, we use total SPN (so that the pre-spawn mortality effects get "baked in" to the S/R relationship and so we don't have to try to simulate it separately)

just in case/for the record:

* total spawners = everything that arrives on the spawning grounds
* effective total spawners = total spawners x pre-spawn mortality
* effective female spawners = effective total spawners x M:F ratio

run size forecast uses EFS. For FRSSI, we've used both ETS and tlSPN at one point or other (and I keep forgetting which was used when - it's all a bit of a blur)

Fab! I've got "learn other Bayesian stats languages" on my list of things to do (eventually) - seeing how you translate the WinBUGS code to something else will be a gentle start. I will test out my collaborator powers shortly.

**Comment by CamFreshwater** [comment]
Sounds good, however none of the SR datasets I have include total spawners I think. When you get a chance could you either send it to me or add it to the data directory in the repo?

**Comment by CamFreshwater** [comment]
Nevermind AMH, I found an .xls that has a TotalAdultSpawners column which I'll use to fit the models. I'll let you know if I have any issues tomorrow.

**Comment by CamFreshwater** [comment]
Unfortunately I wasn't able to get WinBUGS up and running at work, but I've transferred the model to two jags scripts (jagsModels/singleStockLarkin.txt and /singleStockRicker.txt if you'd like to have a look). My parameter estimates are pretty close, but the one for beta is definitely off and I think it's related to the prior.

Ann-Marie could you tell me what your prior for sMax is? It's defined as `Smax ~ dlnorm(log_Shi,1)I(,sShi)` in the larkin_a(v2).odc file. I know sShi is 3x max observed spawner abundance and the rest is pretty clear, I'm just not sure how to interpret that...

Thanks!

**Comment by CamFreshwater** [comment]
Alright I'm fairly certain that all the priors are correct, but my estimates are still varying from the median values in the MCMC files you sent me. I know it's not solely related to the delayed density dependent effects because the Ricker model is also a little off. 

Could you quickly confirm that rickerLL - summary stats tlSPN (log-unif beta).csv (and the Larkin equivalent) were generated using the script you sent me? I'll also try installing and running winbugs again.

I also realized that I saved the relevant model scripts in the salmon-sim repo, where I'm doing all the data prep for the files that will be shared among the other repos. In case you don't want to dig through and find the JAGS models, here's the relevant Ricker model. Please let me know if anyone sees something glaringly wrong!

```
model{
  
  for(i in 1:nCUs){
    alpha[i] ~ dnorm(0, 0.001) 
    #smax[i] ~ dunif(0, upp[i])  #use log-normal instead
    capUpp[i] <- 3*upp[i] #add cap for prior
    logUpp[i] <- log(upp[i])
    smax[i] ~ dlnorm(logUpp[i], 1)I(,capUpp[i]) #prior based on FRSSI documentation
    beta[i] <- 1/smax[i]
    
    tau_R[i] ~ dgamma(0.001, 0.001)
    sig_R[i] <- 1 / sqrt(tau_R[i])

    for(j in 1:nyears[i]){
      lnRSmat[i,j] ~ dnorm(pred[i,j], tau_R[i])  #likelihood function
      pred[i,j] <- alpha[i] - beta[i] * Smat[i,j]  #prediction of log(R/S)
    }  #end for j in nyears
  }  #end for i in nCUs

}
```

**Comment by ann-marieH** [comment]
I should be able to take a closer look at this tomorrow afternoon - not sure if you've talked to Sue/Bronwyn/Gottfried - they were doing a lot of JAGS/WinBUGS/etc. testing for the FR SK run size forecast model re-build and finding that they got different results with different packages. I don't remember how different.

**Comment by CamFreshwater** [comment]
Yeah after talking to Catarina it seems that there are some consistent differences among JAGS vs. winBugs vs. Stan in how prior distributions are incorporated. To be honest, the differences are minor when you look at the actual posterior distributions, but the medians do shift by 0.05-0.1 depending on the CU and parameter. The attached plots show JAGS (red) and winBUGS (blue) posterior distributions for beta (left) and alpha (right) for E. and L. Stuart (other CUs are similar). 

![image](https://user-images.githubusercontent.com/7143825/49886362-4cf57a80-fdee-11e8-89ba-fb2df3f5037e.png)

Does anyone think it's necessary to get closer convergence considering were only changing one CU? If so then personally I would much rather re-estimate all the CUs in JAGS then try to learn winBugs....

**Comment by CamFreshwater** [comment]
One last thing AMH, could you also send me the priors you were using for the Ricker model or else add the relevant script to the repo. Those CUs seem to drift a bit more than the Larkin and I want to make sure I'm being as consistent as possible. Sorry for the torrent of messages!

**Comment by seananderson** [comment]
I'm not sure how many samples are going into to those histograms but those don't look that different to me. MCMC stochasticity from run to run can be pretty high in some cases without a ridiculous number of samples... and an even more ridiculous number of samples in Gibbs sampling world.

**Comment by CamFreshwater** [comment]
I agree Sean. I'm going to proceed with just changing the Shuswap ES samples for now and we can re-evaluate down the line if people are concerned. Thanks for the input!
