### ISSUE TITLE
Harrison and Raft MUs

### ISSUE THREAD

**Issue by CamFreshwater** [CamFreshwater/synchSalmon#8]
Sorry Ann-Marie, more Fraser specific issues. Bouncing between data given to me by other people I'm getting some discrepancies in terms of where CUs should be assigned within MUs. Just to clarify should Harrison River be pooled with the summers or the lates and should Raft be early summer or summer?

**Comment by ann-marieH** [comment]
No worries - it's definitely easier to ask about these things than trying to reconstruct/find answers when the answers are buried somewhere in a stack of IFMPs (if you're lucky). 

Harrison & Raft both in with Summers.  Prior to 2012, Harrison was in with Lates and Raft in with Early Summers.

**Comment by CamFreshwater** [comment]
Right I thought it was something like that! Ok I'm going to use the total run estimates from the catch data you sent me to parameterize forecast uncertainty for each MU because I assume they'll capture the changes in CU distribution. Otherwise all good, thanks!
